Cocktail.create(name: "mojito")
Cocktail.create(name: "gin tonic")
Cocktail.create(name: "cosmopolitan")
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
